### ISSUE TITLE
highstock-release fails

### ISSUE THREAD

**Issue by alan-hobbart** [taptapship/wiredep#196]
I can't get highstock-release to finish in wiredep, any help would be very much appreciated. There seems toi be a problem with lowdash dependency

MY bower.json
{
  "name": "",
  "version": "0.3.2",
  "description": "",
  "authors": [
    ""
  ],
  "license": "MIT",
  "homepage": "",
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components"
  ],
  "devDependencies": {
    
  },
  "dependencies": {
    "highstock-release ": "~2.1.6"
   
  }
}

ERROR when Wiredep runs

bower ECMDERR       Failed to execute "C:\Users\hobbara\AppData\Roaming\npm\gulp
.CMD wiredep", exit code of #1 C:\_TFS\FDR\FDR.WebUI\app\node_modules\wiredep\wi
redep.js:30     ('on-error', opts.onError || function(err) { throw new Error(err
); })                                                        ^ Error: Error: hig
hstock-release  is not installed. Try running `bower install`.     at C:\_TFS\FD
R\FDR.WebUI\app\node_modules\wiredep\wiredep.js:30:56     at C:\_TFS\FDR\FDR.Web
UI\app\node_modules\wiredep\lib\detect-dependencies.js:145:29     at forOwn (C:\
_TFS\FDR\FDR.WebUI\app\node_modules\wiredep\node_modules\lodash\dist\lodash.js:2
105:15)     at Function.forEach (C:\_TFS\FDR\FDR.WebUI\app\node_modules\wiredep\
node_modules\lodash\dist\lodash.js:3302:9)     at detectDependencies (C:\_TFS\FD
R\FDR.WebUI\app\node_modules\wiredep\lib\detect-dependencies.js:34:7)     at wir
edep (C:\_TFS\FDR\FDR.WebUI\app\node_modules\wiredep\wiredep.js:70:39)     at mo
dule.exports (C:\_TFS\FDR\FDR.WebUI\app\gulp.config.js:10:22)     at Object.<ano
nymous> (C:\_TFS\FDR\FDR.WebUI\app\gulpfile.js:5:38)     at Module._compile (mod
ule.js:460:26)     at Object.Module._extensions..js (module.js:478:10)

Additional error details:
C:\_TFS\FDR\FDR.WebUI\app\node_modules\wiredep\wiredep.js:30
    ('on-error', opts.onError || function(err) { throw new Error(err); })
                                                       ^
Error: Error: highstock-release  is not installed. Try running `bower install`.
    at C:\_TFS\FDR\FDR.WebUI\app\node_modules\wiredep\wiredep.js:30:56
    at C:\_TFS\FDR\FDR.WebUI\app\node_modules\wiredep\lib\detect-dependencies.js
:145:29
    at forOwn (C:\_TFS\FDR\FDR.WebUI\app\node_modules\wiredep\node_modules\lodas
h\dist\lodash.js:2105:15)
    at Function.forEach (C:\_TFS\FDR\FDR.WebUI\app\node_modules\wiredep\node_mod
ules\lodash\dist\lodash.js:3302:9)
    at detectDependencies (C:\_TFS\FDR\FDR.WebUI\app\node_modules\wiredep\lib\de
tect-dependencies.js:34:7)
    at wiredep (C:\_TFS\FDR\FDR.WebUI\app\node_modules\wiredep\wiredep.js:70:39)

    at module.exports (C:\_TFS\FDR\FDR.WebUI\app\gulp.config.js:10:22)
    at Object.<anonymous> (C:\_TFS\FDR\FDR.WebUI\app\gulpfile.js:5:38)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by alan-hobbart** [comment]
Fixed, silly mistake. I had a space at the end of highstock-release in the bower.json eg: "highstock-release "
