### ISSUE TITLE
TypeError: must start with number, buffer, array or string :: Node version 4.1

### ISSUE THREAD

**Issue by fedescarpa** [taptapship/wiredep#217]
I get this error when I run the next code with node 4.1.x. it works with node 0.12.x

```js
gulp.src(src.html).pipe(wiredep.stream({ ignorePath: /^(\.\.\/)+/ }))
```

Error:
```
TypeError: must start with number, buffer, array or string
    at fromObject (buffer.js:167:9)
    at new Buffer (buffer.js:58:10)
    at DestroyableTransform._transform (./node_modules/wiredep/wiredep.js:136:23)
    at DestroyableTransform.Transform._read (./node_modules/wiredep/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (./node_modules/wiredep/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (./node_modules/wiredep/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (./node_modules/wiredep/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (./node_modules/wiredep/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
```

**Comment by vitstr** [comment]
@fedescarpa src.html is empty? I have a similar problem.. https://github.com/taptapship/wiredep/issues/219

**Comment by krnlde** [comment]
I get the same issue with node v5.0.0 now. the src.html is not empty and worked well before the update.

Maybe it has something to do with the breaking changes from *Buffer*? See [changelog](https://github.com/nodejs/node/blob/v5.0.0/CHANGELOG.md)

**Comment by fedescarpa** [comment]
src.html is e regex, like ```app/**/*.html```, is not empty. I saw your issue and it works if I pass the src to wiredep stream.

@stephenplusplus, is this a bug or a feature? Thanks!

**Comment by fedescarpa** [comment]
No, src.html is a glob 'src/**/*.html', is not empty

**Comment by krnlde** [comment]
No no no, he means the content of one of the final HTML files from the glob or whatever. For me it **was** the problem. So thank you @vitstr , though the error message could be improved for that one.

**Comment by reddeadpixel** [comment]
I experienced the problem with having a empty SASS partial file. Seems wiredep doesn't like it to have empty files in it's stream, but it won't throw an error if you insert a space or new line in the empty file.

I agree with @krnlde that the error message on this one could be improved. If @vitstr didn't mentioned abt an empty file, I probably still was searching for a needle in a haystack. Thanks!

**Comment by cetrobo** [comment]
i have the same problem as you , how can i fix it ?

**Comment by nvjot94** [comment]
thankssssssssssss.............................
