### ISSUE TITLE
Wiredep weird error!

### ISSUE THREAD

**Issue by sadiqevani** [taptapship/wiredep#231]
Hey,

So, i've been working with wiredep for a long time, and this is the first time i am getting this error, and i cant seem to debug it:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: must start with number, buffer, array or string
    at fromObject (buffer.js:167:9)
    at new Buffer (buffer.js:58:10)
    at DestroyableTransform._transform (/Users/sadiqevani/Laboratory/signage/node_modules/wiredep/wiredep.js:135:23)
    at DestroyableTransform.Transform._read (/Users/sadiqevani/Laboratory/signage/node_modules/wiredep/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/sadiqevani/Laboratory/signage/node_modules/wiredep/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/sadiqevani/Laboratory/signage/node_modules/wiredep/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/sadiqevani/Laboratory/signage/node_modules/wiredep/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/Users/sadiqevani/Laboratory/signage/node_modules/wiredep/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/Users/sadiqevani/Laboratory/signage/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/sadiqevani/Laboratory/signage/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
```

Anyone had a similar issue?

**Comment by sadiqevani** [comment]
Solved.

Issue comes from having empty files.

**Comment by ghost** [comment]
This should be fixed.
