### ISSUE TITLE
After package update

### ISSUE THREAD

**Issue by Phalconline** [taptapship/wiredep#254]
`[11:39:52] 'wiredep' errored after 91 ms
[11:39:52] TypeError: Cannot read property 'length' of undefined
    at flattenGlob (/Users/alexander.sokolovskiy/projects/people/web/app/themes/people/node_modules/glob2base/index.js:9:25)
    at setToBase (/Users/alexander.sokolovskiy/projects/people/web/app/themes/people/node_modules/glob2base/index.js:48:12)
    at module.exports (/Users/alexander.sokolovskiy/projects/people/web/app/themes/people/node_modules/glob2base/index.js:56:19)
    at Object.gs.createStream (/Users/alexander.sokolovskiy/projects/people/web/app/themes/people/node_modules/gulp/node_modules/glob-stream/index.js:34:42)
    at Object.gs.create (/Users/alexander.sokolovskiy/projects/people/web/app/themes/people/node_modules/gulp/node_modules/glob-stream/index.js:76:43)
    at Gulp.src (/Users/alexander.sokolovskiy/projects/people/web/app/themes/people/node_modules/gulp/node_modules/vinyl-fs/lib/src/index.js:33:23)
    at Gulp.<anonymous> (/Users/alexander.sokolovskiy/projects/people/web/app/themes/people/gulpfile.js:276:15)
    at module.exports (/Users/alexander.sokolovskiy/projects/people/web/app/themes/people/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/alexander.sokolovskiy/projects/people/web/app/themes/people/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/alexander.sokolovskiy/projects/people/web/app/themes/people/node_modules/orchestrator/index.js:214:10)
[11:39:52] 'build' errored after 93 ms
[11:39:52] TypeError in plugin 'run-sequence(wiredep)'
Message:
    Cannot read property 'length' of undefined
Stack:
TypeError: Cannot read property 'length' of undefined
    at flattenGlob (/Users/alexander.sokolovskiy/projects/people/web/app/themes/people/node_modules/glob2base/index.js:9:25)
    at setToBase (/Users/alexander.sokolovskiy/projects/people/web/app/themes/people/node_modules/glob2base/index.js:48:12)
    at module.exports (/Users/alexander.sokolovskiy/projects/people/web/app/themes/people/node_modules/glob2base/index.js:56:19)
    at Object.gs.createStream (/Users/alexander.sokolovskiy/projects/people/web/app/themes/people/node_modules/gulp/node_modules/glob-stream/index.js:34:42)
    at Object.gs.create (/Users/alexander.sokolovskiy/projects/people/web/app/themes/people/node_modules/gulp/node_modules/glob-stream/index.js:76:43)
    at Gulp.src (/Users/alexander.sokolovskiy/projects/people/web/app/themes/people/node_modules/gulp/node_modules/vinyl-fs/lib/src/index.js:33:23)
    at Gulp.<anonymous> (/Users/alexander.sokolovskiy/projects/people/web/app/themes/people/gulpfile.js:276:15)
    at module.exports (/Users/alexander.sokolovskiy/projects/people/web/app/themes/people/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/alexander.sokolovskiy/projects/people/web/app/themes/people/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/alexander.sokolovskiy/projects/people/web/app/themes/people/node_modules/orchestrator/index.js:214:10)
[11:39:52] Finished 'default' after 96 ms`

**Comment by Phalconline** [comment]
All Configs default from here
https://github.com/roots/sage
