### ISSUE TITLE
Wiredep with CSS (gulp)

### ISSUE THREAD

**Issue by davidrhoderick** [taptapship/wiredep#273]
I'm having a heck of a time trying to get wiredep to work nicely with CSS.  Generally, I find wiredep to have the kind of documentation that requires a lot of trial-and-error programming and I say that because what does "replace" do?

I've gotten wiredep to work on the first run by setting it up in the following way:

    gulp.src('styles/main.css')
      .pipe(wiredep({
        overrides: {
          'bootstrap': {
            'main': 'dist/css/bootstrap.css'
          }
        },
        fileTypes: {
          css: {
            block: /(([ \t]*)\/\*\s*bower:(\S*)\s*\*\/(\n|\r|.))*?(\/\*\s*endbower\s*\*\/)/gi,
            detect: {
              css: /@import\s['"](.+css)['"];/gi
            },
            replace: {
              css: '@import "{{filePath}}";'
            }
          }
        }
      }))
      .pipe(gulp.dest('styles/'));

And my blocks look like this:

    /* bower:css */
    /* endbower */

On first run, we are great; it works and injects the following way:

    /* bower:css */

    @import '../bower_components/bootstrap/dist/css/bootstrap.css';
    @import '../bower_components/slick-carousel/slick/slick.css';
    @import '../bower_components/slick-carousel/slick/slick-theme.css';
    @import '../bower_components/slick-lightbox/dist/slick-lightbox.css';
    /* endbower */

However, if I stop Gulp and run it again, I get the following error:

    events.js:160
      throw er; // Unhandled 'error' event
      ^

    TypeError: Cannot read property 'replace' of undefined
        at /Users/davidrhoderick/Development/greetings-from-mv/www/node_modules/wiredep/lib/inject-dependencies.js:74:35
        at RegExp.[Symbol.replace] (native)
        at String.replace (native)
        at injectScriptsStream (/Users/davidrhoderick/Development/greetings-from-mv/www/node_modules/wiredep/lib/inject-dependencies.js:133:30)
        at injectDependencies (/Users/davidrhoderick/Development/greetings-from-mv/www/node_modules/wiredep/lib/inject-dependencies.js:30:12)
        at wiredep (/Users/davidrhoderick/Development/greetings-from-mv/www/node_modules/wiredep/wiredep.js:71:39)
        at DestroyableTransform._transform (/Users/davidrhoderick/Development/greetings-from-mv/www/node_modules/wiredep/wiredep.js:136:34)
        at DestroyableTransform.Transform._read (/Users/davidrhoderick/Development/greetings-from-mv/www/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:182:10)
        at DestroyableTransform.Transform._write (/Users/davidrhoderick/Development/greetings-from-mv/www/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:170:83)
        at doWrite (/Users/davidrhoderick/Development/greetings-from-mv/www/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:406:64)

What is going on here?  It looks like the `spacing` variable is undefined in the source code, but why would that be?

**Comment by davidrhoderick** [comment]
Oops, just figured it out; when comparing my css block the scss block provided, I noticed my regex expression had a misplaced parenthesis around newline-type selector.  It was the following:

    /(([ \t]*)\/\*\s*bower:(\S*)\s*\*\/(\n|\r|.))*?(\/\*\s*endbower\s*\*\/)/gi

But it works as and should've been:

    /(([ \t]*)\/\*\s*bower:(\S*)\s*\*\/)(\n|\r|.)*?(\/\*\s*endbower\s*\*\/)/gi
